steps:
  - build: &build
      name: build
      caches:
        - gradle
      script:
        - ./scripts/test.sh
      services:
        - jira


pipelines:

  default:
    - step: *build

definitions:
  services:
    jira:
      image:
        name: kadega/jira-insight:2
        username: $DOCKER_USERNAME
        password: $DOCKER_TOKEN