steps:
  - build: &build
      image: openjdk:8-jdk-alpine
      name: build
      caches:
        - gradle
      script:
        - ./scripts/waitingForJira.sh
        - ./gradlew test --info
      services:
        - docker
        - jira


pipelines:
  default:
    - step: *build

definitions:
  services:
    jira:
      image:
        name: kadega/jira-insight:2
        username: $DOCKER_USERNAME
        password: $DOCKER_TOKEN