steps:
  - build: &build
      name: build
      caches:
        - gradle
      script:
        - ./scripts/waitingForJira.sh
        - ./gradlew test --info
      services:
        - jira


pipelines:

  default:
    - step: *build

definitions:
  services:
    jira:
      memory: 3072
      image:
        name: kadega/jira-insight:2
        username: $DOCKER_USERNAME
        password: $DOCKER_TOKEN